// Generated by CoffeeScript 2.5.1
(function() {
  var a, b, x, y,
    modulo = function(a, b) { return (+a % (b = +b) + b) % b; };

  a = 21;

  b = 21;

  x = true;

  y = false;

  console.log(a === b);

  console.log(a !== b);

  console.log(x && y);

  console.log(x || y);

  console.log(true || false);

  console.log(true || false);

  console.log(a ** b);

  console.log(Math.floor(a / b));

  console.log(modulo(a, b));

}).call(this);
