// Generated by CoffeeScript 2.5.1
(function() {
  var a, b, result;

  a = 15;

  b = 50;

  //Addition
  result = a + b;

  console.log("Addition is " + result);

  //Subtraction
  result = a - b;

  console.log("Subtraction is " + result);

  //Multiplication
  result = a * b;

  console.log("Multiplication is " + result);

  //Division
  result = a / b;

  console.log("Division is " + result);

  //Modulus
  result = b % a;

  console.log("Modulus is " + result);

  //Increment
  a = ++a;

  result = ++a;

  console.log("Increment is " + result);

  //Decrement
  b = --b;

  result = --b;

  console.log("Decrement is " + result);

}).call(this);
