// Generated by CoffeeScript 2.5.1
(function() {
  var a, b, result;

  a = 2; // Bit presentation 10

  b = 3; // Bit presentation 11

  
  //Bitwise AND
  console.log("The result of (a & b) is ");

  result = a & b;

  console.log(result);

  //BitWise OR
  console.log("The result of (a | b) is ");

  result = a | b;

  console.log(result);

  //Bitwise XOR
  console.log("The result of (a ^ b) is ");

  result = a ^ b;

  console.log(result);

  //Bitwise Not
  console.log("The result of (~b) is ");

  result = ~b;

  console.log(result);

  //Left Shift
  console.log("The result of (a << b) is ");

  result = a << b;

  console.log(result);

  //Right Shift
  console.log("The result of (a >> b) is ");

  result = a >> b;

  console.log(result);

}).call(this);
