// Generated by CoffeeScript 2.5.1
(function() {
  //if statement
  var message, score;

  score = 60;

  if (score >= 40) {
    console.log("Congratulations you have passed the examination");
  }

  //if...else statement
  score = 30;

  if (score >= 40) {
    console.log("Congratulations have passed the examination");
  } else {
    console.log("Sorry try again");
  }

  //unless statement
  score = 30;

  if (!(score >= 40)) {
    console.log("Sorry try again");
  }

  //unless...else statement
  score = 60;

  if (!(score >= 40)) {
    console.log("Sorry try again");
  } else {
    console.log("Congratulations you have passed the exam");
  }

  //switch statement
  score = 75;

  message = (function() {
    switch (false) {
      case !(score >= 75):
        return "Congrats your grade is A";
      case !(score >= 60):
        return "Your grade is B";
      case !(score >= 50):
        return "Your grade is C";
      case !(score >= 35):
        return "Your grade is D";
      default:
        return "Your grade is F and you are failed in the exam";
    }
  })();

  console.log(message);

  //Multiple values for when clause in switch statement
  score = 75;

  message = (function() {
    switch (false) {
      case !(score >= 75):
        return "Congrats your grade is A";
      case !(score >= 60):
        return "Your grade is B";
      case !(score >= 50):
        return "Your grade is C";
      case !(score >= 35):
        return "Your grade is D";
      default:
        return "Your grade is F and you are failed in the exam";
    }
  })();

  console.log(message);

  //if-then statement
  score = 60;

  if (score > 40) {
    console.log("Congratulations you have passed the examination");
  }

  //if-then...else statement
  score = 30;

  if (score >= 40) {
    console.log("Congratulations");
  } else {
    console.log("Sorry try again");
  }

  //unless..then statement
  score = 30;

  if (!(score >= 40)) {
    console.log("Sorry try again");
  }

  //unless-then...else statement
  score = 60;

  if (!(score >= 40)) {
    console.log("Sorry try again");
  } else {
    console.log("congratulations.");
  }

  //Postfix if and unless statements
  score = 60;

  if (score > 40) {
    console.log("Congratulations you have passed the examination");
  }

}).call(this);
