// Generated by CoffeeScript 2.5.1
(function() {
  var age, name, subject, verify_name, verify_phone;

  name = "Lokesh";

  age = 24;

  subject = "CSE";

  verify_name = name != null;

  verify_phone = typeof phone !== "undefined" && phone !== null;

  console.log(verify_name);

  console.log(verify_phone);

}).call(this);
