// Generated by CoffeeScript 2.5.1
(function() {
  //Defining a Function
  var add, greet;

  greet = function() {
    return console.log("This is an example of a function");
  };

  //Multi-line Functions
  greet = function() {
    return console.log("Hello how are you");
  };

  //Functions with Arguments
  add = function(a, b) {
    var c;
    c = a + b;
    return console.log("Sum of the two numbers is: " + c);
  };

  //Invoking a Function
  add = function() {
    var a, b, c;
    a = 20;
    b = 30;
    c = a + b;
    return console.log("Sum of the two numbers is: " + c);
  };

  add();

  //Invoking Functions with Arguments
  add = function(a, b) {
    var c;
    c = a + b;
    return console.log("Sum of the two numbers is: " + c);
  };

  add(10, 20);

  
  //Default Arguments
  add = function(a = 1, b = 2) {
    var c;
    c = a + b;
    return console.log("Sum of the two numbers is: " + c);
  };

  add(10, 20);

  //Calling the function with default arguments
  add();

}).call(this);
