// Generated by CoffeeScript 2.5.1
(function() {
  var a, b, result;

  a = true;

  b = false;

  //Logical AND
  console.log("The result of (a && b) is ");

  result = a && b;

  console.log(result);

  //Logical OR
  console.log("The result of (a || b) is ");

  result = a || b;

  console.log(result);

  //Logical NOT
  console.log("The result of !(a && b) is ");

  result = !(a && b);

  console.log(result);

  //Aliases Logical AND
  console.log("The result of (a and b) is ");

  result = a && b;

  console.log(result);

  //Aliases Logical OR
  console.log("The result of (a or b) is ");

  result = a || b;

  console.log(result);

  //Aliases Logical NOT
  console.log("The result of not(a and b) is ");

  result = !(a && b);

  console.log(result);

}).call(this);
