// Generated by CoffeeScript 2.5.1
(function() {
  //while loop
  var count, num;

  console.log("Starting Loop ");

  count = 0;

  while (count < 10) {
    console.log("Current Count : " + count);
    count++;
  }

  console.log("Set the variable to different value and then try");

  //until Loop
  console.log("Starting Loop ");

  count = 0;

  while (!(count > 10)) {
    console.log("Current Count : " + count);
    count++;
  }

  console.log("Set the variable to different value and then try");

  while (true) {
    //The loop variant of while
    num = Math.random() * 8 | 0;
    console.log(num);
    if (num === 5) {
      break;
    }
  }

}).call(this);
